
public void run() throws IOException {
    
    int TEST_CASE = 1;
    while (TEST_CASE-- != 0) {
        n = io.nextInt();
        cs = io.next();
        for (int i = 0; i < 1 << 2; i++) {
            if (can(i)) {
                io.out.println(new String(ans));
                return;
            }
        }
        io.out.println(-1);
    }
}